spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    URL: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8
    mode: HTML
    cache: false
  web:
      resources:
        cache:
          cache control:
            no-cache: true
        static-locations: classpath:/static/
server:
  port: 9000
  servlet:
    encoding:
      charset: utf-8
      force: true


      hikari:
        #连接池名
        pool-name: DateHikariCP
        #最小空闲连接数
        minimum-idle: 5
        #空闲连接中存活最大时间 默认 600000 十分钟
        idle-timeout: 180000
        #最大连接数，默认10
        maximum-pool-size: 10
        #从连接池返回的连接自动提交
        auto-commit: true
        # 连接最大存活时间，0表示永久存活，默认1800000(30分支)max-lifetime: 1800000
        # 连接超时时间，默认30000(30秒)
        connection-timeout: 3000
        #测试连接是否可用的查询语句
        connection-test-query: SELECT 1
        #Mybatis-plus配置
        mybatis-plus:
          #配置Mapper.xml映射文件
          mapper-locations: classpath:*/mapper/*Mapper.xml  #配置MyBatis数据返回类型别名(默认别名是类名)
          type-aliases-package: com.example.seckilldemo.pojo
          # MyBatis SQL打印(方法接口所在的包，不是Mapper.xml所在的包
        logging:
          level:
            com.example.seckilldemo.mapper: debug


